### ISSUE TITLE
module: uninstall, install, update/set module config does not work properly

### ISSUE THREAD

**Issue by BernhardBaumrock** [BernhardBaumrock/RockMigrations#1]
This does not work:
```
// upgrade
  $rm->installModule('RockFinder2');
  $rm->updateModuleConfig('RockFinder2', [
    'url' => uniqid(),
  ]);

// downgrade
  $rm->uninstallModule('RockFinder2');
```

**Comment by jmartsch** [comment]
Please see if this works after my PR https://github.com/BernhardBaumrock/RockMigrations/pull/12

**Comment by BernhardBaumrock** [comment]
thx about the PR regarding the `force` option :) I'll wait for your answer to my comment then I think I can add that to the module.

**Comment by jmartsch** [comment]
> thx about the PR regarding the `force` option :) I'll wait for your answer to my comment then I think I can add that to the module.

I replied you in the PR as a comment. Would be nice if it could be merged soon.
