### ISSUE TITLE
function createTemplate could be replaced by core function

### ISSUE THREAD

**Issue by jmartsch** [BernhardBaumrock/RockMigrations#10]
PW 3.0.170 now has a `$templates->add("name");` method https://processwire.com/blog/posts/pw-3.0.170/
, which could possibly replace the createTemplate function.

https://github.com/BernhardBaumrock/RockMigrations/blob/master/RockMigrations.module.php#L986

Same for the rename function:
`$templates->rename($template, $newName);`

**Comment by BernhardBaumrock** [comment]
Thx for letting me know :) What would be the benefit? We'd have to check for the version and keep the existing method for backwards compatibility anyhow?!

**Comment by jmartsch** [comment]
Just saying that in the future the both methods of your module could become obsolete. But yeah, I knew that you would give this answer, because thats what I thought myself. 
You could replace them, because in my opinion it is better to use native methods. But do whatever you like with the provided information :)
