### ISSUE TITLE
PHP Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated.

### ISSUE THREAD

**Issue by BernhardBaumrock** [BernhardBaumrock/RockMigrations#13]
https://github.com/processwire/processwire-issues/issues/1321

**Comment by BernhardBaumrock** [comment]
@jmartsch where is the fix that you are talking about in the other thread? :) thx for finding the reason for the errors!

**Comment by jmartsch** [comment]
I will provide it as a PR in the next days. Don't have much time atm. But there were multiple issues in the createTemplate, createFields, getField, getTemplate functions.

**Comment by BernhardBaumrock** [comment]
Thx @jmartsch this is fixed now :) 8d415f9545e6a1d4e44c8cb483fc0a54d85b4660
