### ISSUE TITLE
Create tags after each new release

### ISSUE THREAD

**Issue by saschanos** [BernhardBaumrock/RockMigrations#17]
@BernhardBaumrock, would it be possible for you to create a tag after each release? This would make it much more easy to integrate your module into a deployment process. If there's any concerns, let me know.

**Comment by BernhardBaumrock** [comment]
Hi @saschanos of course that would be possible
I just need to get used to that and maybe be a little more careful what I commit and what I tag as release...
It's just that it feels like nobody but me is using rockmigrations anyhow - so I don't waste too much thoughts on this :)
Maybe you could share how you are using the module and how that would be helpful so that I better understand and hopefully learn something that I can also use for my work (so chances rise that I don't forget doing those things), thx

**Comment by saschanos** [comment]
@BernhardBaumrock, that sounds great :). I actually don't think you are the only user of it. According to Packagist, there are 44 installs (https://packagist.org/packages/baumrock/rockmigrations). Thank you for you work, I love your plugin!

I've included your git in Composer, which then runs automatically on deployment. Currently, I then pick a commit myself that I think is stable. However, it would be much better if I could just get the latest release via "composer require" and use that.

Translated with www.DeepL.com/Translator (free version)

**Comment by saschanos** [comment]
@BernhardBaumrock, that sounds great :). I actually don't think you are the only user of it. According to Packagist, there are 44 installs (https://packagist.org/packages/baumrock/rockmigrations). Thank you for you work, I love your plugin!

I've included your git in Composer, which then runs automatically on deployment. Currently, I then pick a commit myself that I think is stable. However, it would be much better if I could just get the latest release via "composer require" and use that.

**Comment by BernhardBaumrock** [comment]
I've created a tag for the latest version

```
git tag v0.0.52
git push origin --tags
```

I'm quite sure I'll forget about tags often so please give me reminders from time to time.

Glad you like the module - it's invaluable for me. Help and contributions (eg helping with the readme to make it easier for newcomers or sharing your thoughts on the forum) always welcome!

Ideally I'd like to create a new version of the module one day as it has become a little messy. Some of the methods I'm not using any more at all. The module evolves every day while working on projects. The next major version would need some better docs and a better way of logging and exception handling...

**Comment by saschanos** [comment]
Perfect :) Thank you so much; will try my best :)
