### ISSUE TITLE
Migration dependencies

### ISSUE THREAD

**Issue by nloyola** [BernhardBaumrock/RockMigrations#22]
I want to add a FieldtypeRepeater and I want the repeater to contain a FieldtypePage. Do I have to create the FieldtypePage in separate migration? The reason is In the FieldtypeRepeater I have to give the *id* of the FieldtypePage i the `repeaterFields` property. 

If I do it in a single migration, the FieldtypePage does not yet have an id.

What is the best way to do this?

**Comment by BernhardBaumrock** [comment]
Please use the ProcessWire forum for support requests, thanks

**Comment by nloyola** [comment]
Thank you. But, should not this be documented?
