### ISSUE TITLE
Repater fields context not applied for the first time

### ISSUE THREAD

**Issue by uiii** [BernhardBaumrock/RockMigrations#24]
Hi, when you add new field to a repeater via `repeaterFields` in `migrate(...)` method the field context is not applied. You have to run migrations again.

Found the problem is the context is set before the field is added to the repeater's template

```php
        // support repeater field array
        if($key === "repeaterFields") {
          $fields = $data[$key];
          $addFields = [];
          $index = 0;
          foreach($fields as $i=>$_field) {
            if(is_string($i)) {
              // we've got a field with field context info here
              $fieldname = $i;
              $fielddata = $_field;
              $this->setFieldData( // <------- THIS RUNS FIRST
                $fieldname,
                $fielddata,
                $this->getRepeaterTemplate($field)
              );
            }
            else {
              // field without field context info
              $fieldname = $_field;
            }
            $addFields[$index] = $this->fields->get((string)$fieldname)->id;
            $index++;
          }
          $data[$key] = $addFields;

          // add fields to repeater template
          if($tpl = $this->getRepeaterTemplate($field)) {
            $this->addFieldsToTemplate($addFields, $tpl); // <------- THIS RUNS AFTER
          }
        }
```

Got an idea, maybe you can replace this while code by this modified code from `setTemplateData` method

```php
        if(($key === 'repeaterFields' || $key === 'repeaterFields-') AND is_array($data[$key])) {
          // if the key is 'repeaterFields' we set the fields
          // if the key is 'repeaterFields-' we set fields and remove others
          $removeOthers = $k==='repeaterFields-';
          $this->setTemplateFields($this->getRepeaterTemplate($field), $data[$key], $removeOthers);
        }
```

**Comment by uiii** [comment]
But I haven't tested it, you know your code better to know if this can work.

**Comment by BernhardBaumrock** [comment]
thx for finding thix :) the latest commit should fix this, can you please confirm that?

**Comment by uiii** [comment]
Hey thanks, that was quick. It works. The code I proposed is not usable? It would be unified with templates.

**Comment by BernhardBaumrock** [comment]
I don't know, it was easier for me to fix it my way than understanding yours ;)

**Comment by uiii** [comment]
Ah, I just copied (and modified accordingly) a code you have in `setTemplateData` which sets the fields for template :-)

**Comment by uiii** [comment]
so it can also support the `-` sign for removing other fields

**Comment by uiii** [comment]
But you probably know if it is suitable or not

**Comment by BernhardBaumrock** [comment]
Yeah that would be better I guess. I'm not working much with repeaters so if you do I'll be happy to add this via PR.

**Comment by uiii** [comment]
Ok, I'll try.
