### ISSUE TITLE
Documentation for editing a Matrix field?

### ISSUE THREAD

**Issue by ryanscherler** [BernhardBaumrock/RockMigrations#7]
I first want to say thanks SO much for creating support for Matrix fields! This is a huge help for our team which extensively uses matrix fields for structured content on our client sites. 

One issue we have is how to best create a migration to edit an existing matrix field (e.g. add a field (and related sub-fields, attributes etc.), remove a field, as well as set options for fields such as the column width etc. via a migration. 

Is there a good resource or example for using this [new method](https://github.com/BernhardBaumrock/RockMigrations/blob/74ad04ae2ab8ab0d303c423e77ab9c2521d198c4/RockMigrations.module.php#L345) you can point me to?

Thanks again!

**Comment by BernhardBaumrock** [comment]
You have to thank https://processwire.com/talk/profile/7644-acomadi/ who sponsored the update - I'm not using any matrix fields with RockMigrations - I'm building my own matrix field :) 

Did you see this?
https://github.com/BernhardBaumrock/RockMigrations/blob/74ad04ae2ab8ab0d303c423e77ab9c2521d198c4/RockMigrations.module.php#L791-L839

**Comment by ryanscherler** [comment]
I did see the method - just not sure how to use it in an example migration file that calls this?

**Comment by BernhardBaumrock** [comment]
```php
      * Usage: 
      *  $rm->setMatrixItems('your_matrix_field', [ 
      *    'foo' => [ 
      *      'label' => 'foo label', 
      *      'fields' => ['field1', 'field2'], 
      *    ], 
      *    'bar' => [ 
      *      'label' => 'bar label', 
      *      'fields' => ['field1', 'field3'], 
      *    ], 
      *  ], true); 
```
What is unclear with that docblock?

**Comment by ryanscherler** [comment]
Oh my - I totally missed the "usage:" info about that field before (maybe its new on some methods?) Thanks so much!

**Comment by ryanscherler** [comment]
One other quick question, is it possible to set matrix item(s) field meta (column width etc.) at the same time? I am guessing it probably is a separate migration method since it requires a 'save'?

**Comment by BernhardBaumrock** [comment]
> Oh my - I totally missed the "usage:" info about that field before (maybe its new on some methods?) Thanks so much!

That's why I was a little confused about your question ;)

> One other quick question, is it possible to set matrix item(s) field meta (column width etc.) at the same time? I am guessing it probably is a separate migration method since it requires a 'save'?

Have you tried it? I think it should just work...

**Comment by ryanscherler** [comment]
> [...] is it possible to set matrix item(s) field meta (column width etc.) at the same time? I am guessing it probably is a separate migration method since it requires a 'save'?

> Have you tried it? I think it should just work...

I haven't tried this as I assumed that (much like the UI), you first had to 'save' the main matrix field to allow customization of the child fields scoped to the parent (column width etc.). I'll give it a run and see - thanks! This is such a powerful module (we are using a CLI tool to directly work with the module rather than via another module).

**Comment by BernhardBaumrock** [comment]
The way the migrate() method works is that it first creates all fields and templates that are listed and THEN sets all the properties. This makes sure that you can reference fields by name that are created in the same migration.

This would work:

```php
$rm->migrate([
  'templates' => ['footpl' => ['fields' => ['barfield']]],
  'fields' => ['barfield' => ['type' => 'text', 'columnWidth' => 50]],
]);
```

> This is such a powerful module (we are using a CLI tool to directly work with the module rather than via another module).

Great to hear that. This was an important point for me - RM does really not care where it is executed, wheter from a module, a template file, or any other script (within the PW scope of course).

Would be great to get a writeup in the modules thread about how you are using RM and why. I think many people are still missing the power and ease of the module...

PS: I tend to set only the necessary parts of the field (like file extensions that needs to be available on ajax calls) via migrations and everything else via hook (eg label, columnWidth, etc on ProcessPageEdit::buildForm) --> that makes migrations easy and the setup a lot more flexible.

**Comment by ryanscherler** [comment]
Wow that is truly awesome! Works perfectly. 

Yes I'll definitely do a writeup about how we integrated [Artisan](https://laravel.com/docs/7.x/artisan) (Laravel CLI) into our ProcessWire project and then [wrote a custom command](https://gist.github.com/ryanscherler/40d014e249a0547f387e3581bd398bdc) to do the migrations (it does versioning etc. to mimic the laravel `artisan migrate` and `artisan make:migration`  API

**Comment by BernhardBaumrock** [comment]
Thx, really looking forward to reading that! :)

**Comment by ryanscherler** [comment]
So after some more work with the module, it seems there are some things I can't wrap my head around. We are looking to add an *existing field as a matrix item and then set context specific settings for that added field. ALSO, it seems $wipe = false is not working as expected (all fields disappear when hoping to just append a new field onto the matrix). Here is some code we are using in the 'after' hook:

```php
return [
    'after' => function(RockMigrations $rm) {
        // Edit field: widgets_section (ProFields: Repeater Matrix)

        // Get an existing field by name
        $emailField = $rm->getField('email');
        
        // Update specific meta data about this field (though it seems to do this globally, 
        // and can't figure out how to contextually change it for JUST the matrix field below.
        $rm->setFieldData('email', [
            'label' => 'Label just for email within highlight matrix field',
            'columnWidth' => 50,
        ]);

        $rm->setMatrixItems('widgets_section', [ 
            'highlight' => [ 
                'label' => 'Highlights bla bla test', 
                'fields' => [
                    $emailField, // add existing field as matrix item
                ],
            ], 
        ], false); // settings to FALSE still seems to wipe out all other matrix items for 'highlight' and just adds email
    },
];
```

Sorry to be a pain - I am sure I am just missing something?

**Comment by BernhardBaumrock** [comment]
Sorry for that, but I guess you can understand that I don't want to provide support for something that I don't need and that is related to a paid module of Ryan. If you need support I'm available to hire on an hourly rate for such things. That's how these matrix additions found their way into the module: Someone requested them and paid for it ;)

**Comment by samhowat** [comment]
@BernhardBaumrock I'd be interested in sponsoring the update. 

To take things further, I've edited my comment with these notes: 

Ryan is building a migration system for us that utilizes your plugin. A big chunk of our system uses repeaters, matrixes and much of the time we're moving fields around so I will happily pay to ensure that your plugin supports more complex scenarios. 

I will happily pay to have you help with scenarios like this (as they arise) to improve the plugin. How do we make that happen?

**Comment by BernhardBaumrock** [comment]
@samhowat sorry for the delay, I don't check github every day... can you please write me a PM on the forum so that we can chat about that?
