### ISSUE TITLE
Do we support FieldtypeOptions (core module)?

### ISSUE THREAD

**Issue by apeisa** [BernhardBaumrock/RockMigrations#8]
Trying to use FieldtypeOptions, but for some reason cannot figure out what is the syntax (using migrate method, array syntax) for using it? Or is it not supported yet?

**Comment by BernhardBaumrock** [comment]
Hi apeisa,
it's not perfect, but it works: https://github.com/BernhardBaumrock/RockMigrations/blob/master/README.md#options-fields
